package net.hypnozcore.hypnozcore.dto;

import io.swagger.annotations.ApiModel;
import lombok.AccessLevel;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.FieldDefaults;

import javax.validation.constraints.Size;

@ApiModel("Application Dto")
@Data
@FieldDefaults(level = AccessLevel.PRIVATE)
@EqualsAndHashCode(callSuper = true)
public class ChronosDto extends AbstractDto {
    private int chrNature;
    @Size(max = 30)
    private String chrSerie;
    @Size(max = 50)
    private String chrNom;
    private int chrPrive;
    @Size(max = 20)
    private String chrService;
    private int chrNbCar;
    private int chrMode;
    private int chrFormat;
    @Size(max = 4)
    private String chrPrefixe;
    private long chrNum;
    private long chrNumAn;
    private long chrNum01;
    private long chrNum02;
    private long chrNum03;
    private long chrNum04;
    private long chrNum05;
    private long chrNum06;
    private long chrNum07;
    private long chrNum08;
    private long chrNum09;
    private long chrNum10;
    private long chrNum11;
    private long chrNum12;
    @Size(max = 4)
    private String chrSufixe;
    @Size(max = 10)
    private String chrJournal;
    @Size(max = 10)
    private String chrJournalOd;
    @Size(max = 10)
    private String chrPeriode;
    private long chrNum1;
    private long chrNumAn1;
    private long chrNum011;
    private long chrNum021;
    private long chrNum031;
    private long chrNum041;
    private long chrNum051;
    private long chrNum061;
    private long chrNum071;
    private long chrNum081;
    private long chrNum091;
    private long chrNum101;
    private long chrNum111;
    private long chrNum121;
    @Size(max = 4)
    private String chrPrefixe1;
    @Size(max = 4)
    private String chrSufixe1;
    private long chrNum2;
    private long chrNumAn2;
    private long chrNum012;
    private long chrNum022;
    private long chrNum032;
    private long chrNum042;
    private long chrNum052;
    private long chrNum062;
    private long chrNum072;
    private long chrNum082;
    private long chrNum092;
    private long chrNum102;
    private long chrNum112;
    private long chrNum122;
    @Size(max = 4)
    private String chrPrefixe2;
    @Size(max = 4)
    private String chrSufixe2;
    private long chrNum3;
    private long chrNumAn3;
    private long chrNum013;
    private long chrNum023;
    private long chrNum033;
    private long chrNum043;
    private long chrNum053;
    private long chrNum063;
    private long chrNum073;
    private long chrNum083;
    private long chrNum093;
    private long chrNum103;
    private long chrNum113;
    private long chrNum123;
    @Size(max = 4)
    private String chrPrefixe3;
    @Size(max = 4)
    private String chrSufixe3;
    private long chrNum4;
    private long chrNumAn4;
    private long chrNum014;
    private long chrNum024;
    private long chrNum034;
    private long chrNum044;
    private long chrNum054;
    private long chrNum064;
    private long chrNum074;
    private long chrNum084;
    private long chrNum094;
    private long chrNum104;
    private long chrNum114;
    private long chrNum124;
    @Size(max = 4)
    private String chrPrefixe4;
    @Size(max = 4)
    private String chrSufixe4;
    private long chrNum5;
    private long chrNumAn5;
    private long chrNum015;
    private long chrNum025;
    private long chrNum035;
    private long chrNum045;
    private long chrNum055;
    private long chrNum065;
    private long chrNum075;
    private long chrNum085;
    private long chrNum095;
    private long chrNum105;
    private long chrNum115;
    private long chrNum125;
    @Size(max = 4)
    private String chrPrefixe5;
    @Size(max = 4)
    private String chrSufixe5;
    private long chrNum6;
    private long chrNumAn6;
    private long chrNum016;
    private long chrNum026;
    private long chrNum036;
    private long chrNum046;
    private long chrNum056;
    private long chrNum066;
    private long chrNum076;
    private long chrNum086;
    private long chrNum096;
    private long chrNum106;
    private long chrNum116;
    private long chrNum126;
    @Size(max = 4)
    private String chrPrefixe6;
    @Size(max = 4)
    private String chrSufixe6;
    private long chrNum7;
    private long chrNumAn7;
    private long chrNum017;
    private long chrNum027;
    private long chrNum037;
    private long chrNum047;
    private long chrNum057;
    private long chrNum067;
    private long chrNum077;
    private long chrNum087;
    private long chrNum097;
    private long chrNum107;
    private long chrNum117;
    private long chrNum127;
    @Size(max = 4)
    private String chrPrefixe7;
    @Size(max = 4)
    private String chrSufixe7;
    private long chrNum8;
    private long chrNumAn8;
    private long chrNum018;
    private long chrNum028;
    private long chrNum038;
    private long chrNum048;
    private long chrNum058;
    private long chrNum068;
    private long chrNum078;
    private long chrNum088;
    private long chrNum098;
    private long chrNum108;
    private long chrNum118;
    private long chrNum128;
    @Size(max = 4)
    private String chrPrefixe8;
    @Size(max = 4)
    private String chrSufixe8;
    private long chrNum9;
    private long chrNumAn9;
    private long chrNum019;
    private long chrNum029;
    private long chrNum039;
    private long chrNum049;
    private long chrNum059;
    private long chrNum069;
    private long chrNum079;
    private long chrNum089;
    private long chrNum099;
    private long chrNum109;
    private long chrNum119;
    private long chrNum129;
    @Size(max = 4)
    private String chrPrefixe9;
    @Size(max = 4)
    private String chrSufixe9;
    private long chrNumA;
    private long chrNumAnA;
    private long chrNum01A;
    private long chrNum02A;
    private long chrNum03A;
    private long chrNum04A;
    private long chrNum05A;
    private long chrNum06A;
    private long chrNum07A;
    private long chrNum08A;
    private long chrNum09A;
    private long chrNum10A;
    private long chrNum11A;
    private long chrNum12A;
    @Size(max = 4)
    private String chrPrefixeA;
    @Size(max = 4)
    private String chrSufixeA;
    @Size(max = 10)
    private String chrCodeCaisse;
    private int chrModeCaisse;
    private Long chrIdStr;
    private Long chrNum0110;
    private Long chrNum0111;
    private Long chrNum0121;
    private Long chrNum0131;
    private Long chrNum0141;
    private Long chrNum0151;
    private Long chrNum0161;
    private Long chrNum0171;
    private Long chrNum0181;
    private Long chrNum0191;
    private Long chrNum01a;
    private Long chrNum0210;
    private Long chrNum0211;
    private Long chrNum0221;
    private Long chrNum0231;
    private Long chrNum0241;
    private Long chrNum0251;
    private Long chrNum0261;
    private Long chrNum0271;
    private Long chrNum0281;
    private Long chrNum0291;
    private Long chrNum02a;
    private Long chrNum0310;
    private Long chrNum0311;
    private Long chrNum0321;
    private Long chrNum0331;
    private Long chrNum0341;
    private Long chrNum0351;
    private Long chrNum0361;
    private Long chrNum0371;
    private Long chrNum0381;
    private Long chrNum0391;
    private Long chrNum03a;
    private Long chrNum0410;
    private Long chrNum0411;
    private Long chrNum0421;
    private Long chrNum0431;
    private Long chrNum0441;
    private Long chrNum0451;
    private Long chrNum0461;
    private Long chrNum0471;
    private Long chrNum0481;
    private Long chrNum0491;
    private Long chrNum04a;
    private Long chrNum0510;
    private Long chrNum0511;
    private Long chrNum0521;
    private Long chrNum0531;
    private Long chrNum0541;
    private Long chrNum0551;
    private Long chrNum0561;
    private Long chrNum0571;
    private Long chrNum0581;
    private Long chrNum0591;
    private Long chrNum05a;
    private Long chrNum0610;
    private Long chrNum0611;
    private Long chrNum0621;
    private Long chrNum0631;
    private Long chrNum0641;
    private Long chrNum0651;
    private Long chrNum0661;
    private Long chrNum0671;
    private Long chrNum0681;
    private Long chrNum0691;
    private Long chrNum06a;
    private Long chrNum0710;
    private Long chrNum0711;
    private Long chrNum0721;
    private Long chrNum0731;
    private Long chrNum0741;
    private Long chrNum0751;
    private Long chrNum0761;
    private Long chrNum0771;
    private Long chrNum0781;
    private Long chrNum0791;
    private Long chrNum07a;
    private Long chrNum0810;
    private Long chrNum0811;
    private Long chrNum0821;
    private Long chrNum0831;
    private Long chrNum0841;
    private Long chrNum0851;
    private Long chrNum0861;
    private Long chrNum0871;
    private Long chrNum0881;
    private Long chrNum0891;
    private Long chrNum08a;
    private Long chrNum0910;
    private Long chrNum0911;
    private Long chrNum0921;
    private Long chrNum0931;
    private Long chrNum0941;
    private Long chrNum0951;
    private Long chrNum0961;
    private Long chrNum0971;
    private Long chrNum0981;
    private Long chrNum0991;
    private Long chrNum09a;
    private Long chrNum13;
    private Long chrNum1010;
    private Long chrNum1011;
    private Long chrNum1021;
    private Long chrNum1031;
    private Long chrNum1041;
    private Long chrNum1051;
    private Long chrNum1061;
    private Long chrNum1071;
    private Long chrNum1081;
    private Long chrNum1091;
    private Long chrNum10a;
    private Long chrNum1110;
    private Long chrNum1111;
    private Long chrNum1121;
    private Long chrNum1131;
    private Long chrNum1141;
    private Long chrNum1151;
    private Long chrNum1161;
    private Long chrNum1171;
    private Long chrNum1181;
    private Long chrNum1191;
    private Long chrNum11a;
    private Long chrNum1210;
    private Long chrNum1211;
    private Long chrNum1221;
    private Long chrNum1231;
    private Long chrNum1241;
    private Long chrNum1251;
    private Long chrNum1261;
    private Long chrNum1271;
    private Long chrNum1281;
    private Long chrNum1291;
    private Long chrNum12a;
    private Long chrNum21;
    private Long chrNum31;
    private Long chrNum41;
    private Long chrNum51;
    private Long chrNum61;
    private Long chrNum71;
    private Long chrNum81;
    private Long chrNum91;
    private Long chrNuma;
    private Long chrNumAn11;
    private Long chrNumAn21;
    private Long chrNumAn31;
    private Long chrNumAn41;
    private Long chrNumAn51;
    private Long chrNumAn61;
    private Long chrNumAn71;
    private Long chrNumAn81;
    private Long chrNumAn91;
    private Long chrNumAna;
    @Size(max = 255)
    private String chrPrefixe11;
    @Size(max = 255)
    private String chrPrefixe21;
    @Size(max = 255)
    private String chrPrefixe31;
    @Size(max = 255)
    private String chrPrefixe41;
    @Size(max = 255)
    private String chrPrefixe51;
    @Size(max = 255)
    private String chrPrefixe61;
    @Size(max = 255)
    private String chrPrefixe71;
    @Size(max = 255)
    private String chrPrefixe81;
    @Size(max = 255)
    private String chrPrefixe91;
    @Size(max = 255)
    private String chrPrefixea;
    @Size(max = 255)
    private String chrSufixe11;
    @Size(max = 255)
    private String chrSufixe21;
    @Size(max = 255)
    private String chrSufixe31;
    @Size(max = 255)
    private String chrSufixe41;
    @Size(max = 255)
    private String chrSufixe51;
    @Size(max = 255)
    private String chrSufixe61;
    @Size(max = 255)
    private String chrSufixe71;
    @Size(max = 255)
    private String chrSufixe81;
    @Size(max = 255)
    private String chrSufixe91;
    @Size(max = 255)
    private String chrSufixea;

}